import { Inter } from 'next/font/google'
import './globals.css'
import AuthProvider from '@/components/auth/AuthProvider'
import { Toaster } from 'react-hot-toast'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'TreeHouse.com',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
     <body className={`bg-[#0d0c22] ${inter.className} text-white`}>
      <AuthProvider>
        {children}
      </AuthProvider>
      <Toaster />
        </body>
    </html>
  )
}
